import { NextRequest, NextResponse } from "next/server";
import { getSession } from "@/lib/session-store";

export const dynamic = 'force-dynamic';

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ sessionId: string }> }
) {
  try {
    const { sessionId } = await params;
    const session = getSession(sessionId);

    if (!session) {
      return NextResponse.json(
        { error: "Session not found" },
        { status: 404 }
      );
    }

    if (session.status !== "complete" || !session.summary) {
      return NextResponse.json(
        { error: "Session not complete or missing summary" },
        { status: 400 }
      );
    }

    // Generate NotebookLM-formatted content
    const content = generateNotebookLMContent(session);

    // Return as downloadable text file
    return new NextResponse(content, {
      headers: {
        "Content-Type": "text/plain; charset=utf-8",
        "Content-Disposition": `attachment; filename="${sanitizeFilename(session.topicName)}-study-guide.txt"`,
      },
    });
  } catch (error) {
    console.error("Export API error:", error);
    return NextResponse.json(
      { error: "Failed to export" },
      { status: 500 }
    );
  }
}

function generateNotebookLMContent(session: any): string {
  const { topicName, urls, transcripts, summary } = session;

  const successfulTranscripts = transcripts?.filter((t: any) => t.success) || [];
  const combinedTranscript = successfulTranscripts
    .map((t: any) => `[${t.platform.toUpperCase()}]\n${t.transcript}`)
    .join("\n\n---\n\n");

  return `TOPIC: ${topicName}

================================================================================
SOURCES:
================================================================================
${urls.map((url: string) => `- ${url}`).join("\n")}

================================================================================
TRANSCRIPT:
================================================================================
${combinedTranscript}

================================================================================
SUMMARY:
================================================================================
${summary.summary}

================================================================================
KEY TAKEAWAYS:
================================================================================
${summary.keyTakeaways}

================================================================================
HOW TO APPLY:
================================================================================
${summary.howToApply}

================================================================================
STUDY QUESTIONS:
================================================================================
${summary.studyQuestions}

================================================================================
CONNECTIONS AND PATTERNS:
================================================================================
${summary.connectionsAndPatterns}

================================================================================
Generated by Content Study Tool
Date: ${new Date().toISOString()}
================================================================================
`;
}

function sanitizeFilename(name: string): string {
  return name
    .replace(/[^a-z0-9]/gi, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "")
    .toLowerCase()
    .slice(0, 50);
}
